version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  deathfire-arsenal:
    build: .
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis:6379
    ports:
      - "8080:8080"
